Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel7"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.hostname = "redis-cluster"
  config.vm.synced_folder "./data", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y epel-release
    sudo yum install -y redis
  SHELL
end